spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 202808260658-18vomekogpd84s8dmnf0clpepldqvlpj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot